// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        v6.32.0--rc1
// source: websocket/v1/websocket.proto

package v1

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type MsgType int32

const (
	MsgType_LOGIN    MsgType = 0
	MsgType_CHAT     MsgType = 1
	MsgType_POSITION MsgType = 2
)

// Enum value maps for MsgType.
var (
	MsgType_name = map[int32]string{
		0: "LOGIN",
		1: "CHAT",
		2: "POSITION",
	}
	MsgType_value = map[string]int32{
		"LOGIN":    0,
		"CHAT":     1,
		"POSITION": 2,
	}
)

func (x MsgType) Enum() *MsgType {
	p := new(MsgType)
	*p = x
	return p
}

func (x MsgType) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (MsgType) Descriptor() protoreflect.EnumDescriptor {
	return file_websocket_v1_websocket_proto_enumTypes[0].Descriptor()
}

func (MsgType) Type() protoreflect.EnumType {
	return &file_websocket_v1_websocket_proto_enumTypes[0]
}

func (x MsgType) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use MsgType.Descriptor instead.
func (MsgType) EnumDescriptor() ([]byte, []int) {
	return file_websocket_v1_websocket_proto_rawDescGZIP(), []int{0}
}

type GatewayMessage struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Type          MsgType                `protobuf:"varint,1,opt,name=type,proto3,enum=websocket.v1.MsgType" json:"type,omitempty"`
	Data          string                 `protobuf:"bytes,2,opt,name=data,proto3" json:"data,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GatewayMessage) Reset() {
	*x = GatewayMessage{}
	mi := &file_websocket_v1_websocket_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GatewayMessage) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GatewayMessage) ProtoMessage() {}

func (x *GatewayMessage) ProtoReflect() protoreflect.Message {
	mi := &file_websocket_v1_websocket_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GatewayMessage.ProtoReflect.Descriptor instead.
func (*GatewayMessage) Descriptor() ([]byte, []int) {
	return file_websocket_v1_websocket_proto_rawDescGZIP(), []int{0}
}

func (x *GatewayMessage) GetType() MsgType {
	if x != nil {
		return x.Type
	}
	return MsgType_LOGIN
}

func (x *GatewayMessage) GetData() string {
	if x != nil {
		return x.Data
	}
	return ""
}

type LoginInput struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Phone         string                 `protobuf:"bytes,1,opt,name=phone,proto3" json:"phone,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *LoginInput) Reset() {
	*x = LoginInput{}
	mi := &file_websocket_v1_websocket_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *LoginInput) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LoginInput) ProtoMessage() {}

func (x *LoginInput) ProtoReflect() protoreflect.Message {
	mi := &file_websocket_v1_websocket_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LoginInput.ProtoReflect.Descriptor instead.
func (*LoginInput) Descriptor() ([]byte, []int) {
	return file_websocket_v1_websocket_proto_rawDescGZIP(), []int{1}
}

func (x *LoginInput) GetPhone() string {
	if x != nil {
		return x.Phone
	}
	return ""
}

type LoginOutput struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Token         string                 `protobuf:"bytes,1,opt,name=token,proto3" json:"token,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *LoginOutput) Reset() {
	*x = LoginOutput{}
	mi := &file_websocket_v1_websocket_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *LoginOutput) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LoginOutput) ProtoMessage() {}

func (x *LoginOutput) ProtoReflect() protoreflect.Message {
	mi := &file_websocket_v1_websocket_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LoginOutput.ProtoReflect.Descriptor instead.
func (*LoginOutput) Descriptor() ([]byte, []int) {
	return file_websocket_v1_websocket_proto_rawDescGZIP(), []int{2}
}

func (x *LoginOutput) GetToken() string {
	if x != nil {
		return x.Token
	}
	return ""
}

type ChatInput struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ChatInput) Reset() {
	*x = ChatInput{}
	mi := &file_websocket_v1_websocket_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ChatInput) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ChatInput) ProtoMessage() {}

func (x *ChatInput) ProtoReflect() protoreflect.Message {
	mi := &file_websocket_v1_websocket_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ChatInput.ProtoReflect.Descriptor instead.
func (*ChatInput) Descriptor() ([]byte, []int) {
	return file_websocket_v1_websocket_proto_rawDescGZIP(), []int{3}
}

type ChatOutput struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ChatOutput) Reset() {
	*x = ChatOutput{}
	mi := &file_websocket_v1_websocket_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ChatOutput) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ChatOutput) ProtoMessage() {}

func (x *ChatOutput) ProtoReflect() protoreflect.Message {
	mi := &file_websocket_v1_websocket_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ChatOutput.ProtoReflect.Descriptor instead.
func (*ChatOutput) Descriptor() ([]byte, []int) {
	return file_websocket_v1_websocket_proto_rawDescGZIP(), []int{4}
}

type PostiionInput struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PostiionInput) Reset() {
	*x = PostiionInput{}
	mi := &file_websocket_v1_websocket_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PostiionInput) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PostiionInput) ProtoMessage() {}

func (x *PostiionInput) ProtoReflect() protoreflect.Message {
	mi := &file_websocket_v1_websocket_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PostiionInput.ProtoReflect.Descriptor instead.
func (*PostiionInput) Descriptor() ([]byte, []int) {
	return file_websocket_v1_websocket_proto_rawDescGZIP(), []int{5}
}

type PostiionOutput struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PostiionOutput) Reset() {
	*x = PostiionOutput{}
	mi := &file_websocket_v1_websocket_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PostiionOutput) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PostiionOutput) ProtoMessage() {}

func (x *PostiionOutput) ProtoReflect() protoreflect.Message {
	mi := &file_websocket_v1_websocket_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PostiionOutput.ProtoReflect.Descriptor instead.
func (*PostiionOutput) Descriptor() ([]byte, []int) {
	return file_websocket_v1_websocket_proto_rawDescGZIP(), []int{6}
}

var File_websocket_v1_websocket_proto protoreflect.FileDescriptor

const file_websocket_v1_websocket_proto_rawDesc = "" +
	"\n" +
	"\x1cwebsocket/v1/websocket.proto\x12\fwebsocket.v1\"O\n" +
	"\x0eGatewayMessage\x12)\n" +
	"\x04type\x18\x01 \x01(\x0e2\x15.websocket.v1.MsgTypeR\x04type\x12\x12\n" +
	"\x04data\x18\x02 \x01(\tR\x04data\"\"\n" +
	"\n" +
	"LoginInput\x12\x14\n" +
	"\x05phone\x18\x01 \x01(\tR\x05phone\"#\n" +
	"\vLoginOutput\x12\x14\n" +
	"\x05token\x18\x01 \x01(\tR\x05token\"\v\n" +
	"\tChatInput\"\f\n" +
	"\n" +
	"ChatOutput\"\x0f\n" +
	"\rPostiionInput\"\x10\n" +
	"\x0ePostiionOutput*,\n" +
	"\aMsgType\x12\t\n" +
	"\x05LOGIN\x10\x00\x12\b\n" +
	"\x04CHAT\x10\x01\x12\f\n" +
	"\bPOSITION\x10\x02BI\n" +
	"\x17dev.kratos.websocket.v1B\x10WebsocketProtoV1P\x01Z\x1aMMORPG/api/websocket/v1;v1b\x06proto3"

var (
	file_websocket_v1_websocket_proto_rawDescOnce sync.Once
	file_websocket_v1_websocket_proto_rawDescData []byte
)

func file_websocket_v1_websocket_proto_rawDescGZIP() []byte {
	file_websocket_v1_websocket_proto_rawDescOnce.Do(func() {
		file_websocket_v1_websocket_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_websocket_v1_websocket_proto_rawDesc), len(file_websocket_v1_websocket_proto_rawDesc)))
	})
	return file_websocket_v1_websocket_proto_rawDescData
}

var file_websocket_v1_websocket_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_websocket_v1_websocket_proto_msgTypes = make([]protoimpl.MessageInfo, 7)
var file_websocket_v1_websocket_proto_goTypes = []any{
	(MsgType)(0),           // 0: websocket.v1.MsgType
	(*GatewayMessage)(nil), // 1: websocket.v1.GatewayMessage
	(*LoginInput)(nil),     // 2: websocket.v1.LoginInput
	(*LoginOutput)(nil),    // 3: websocket.v1.LoginOutput
	(*ChatInput)(nil),      // 4: websocket.v1.ChatInput
	(*ChatOutput)(nil),     // 5: websocket.v1.ChatOutput
	(*PostiionInput)(nil),  // 6: websocket.v1.PostiionInput
	(*PostiionOutput)(nil), // 7: websocket.v1.PostiionOutput
}
var file_websocket_v1_websocket_proto_depIdxs = []int32{
	0, // 0: websocket.v1.GatewayMessage.type:type_name -> websocket.v1.MsgType
	1, // [1:1] is the sub-list for method output_type
	1, // [1:1] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_websocket_v1_websocket_proto_init() }
func file_websocket_v1_websocket_proto_init() {
	if File_websocket_v1_websocket_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_websocket_v1_websocket_proto_rawDesc), len(file_websocket_v1_websocket_proto_rawDesc)),
			NumEnums:      1,
			NumMessages:   7,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_websocket_v1_websocket_proto_goTypes,
		DependencyIndexes: file_websocket_v1_websocket_proto_depIdxs,
		EnumInfos:         file_websocket_v1_websocket_proto_enumTypes,
		MessageInfos:      file_websocket_v1_websocket_proto_msgTypes,
	}.Build()
	File_websocket_v1_websocket_proto = out.File
	file_websocket_v1_websocket_proto_goTypes = nil
	file_websocket_v1_websocket_proto_depIdxs = nil
}
