server:
  id: fA4fO2uE3tV5zL4
  name: gateway
  version: 1.0.0
  http:
    addr: 0.0.0.0:8001
    timeout: 1s
  grpc:
    addr: 0.0.0.0:9001
    timeout: 1s
data:
  database:
    driver: mysql
    source: root:root@tcp(127.0.0.1:3306)/test?parseTime=True&loc=Local
  redis:
    addr: 127.0.0.1:6379
    read_timeout: 0.2s
    write_timeout: 0.2s
tracer:
  addr: localhost:4318
registry:
  consul:
    addrs:
      - 127.0.0.1:8500
